version: '3.8'

services:
#  backend:
#    image: backend_image:latest  # Replace with the actual backend image
#    ports:
#      - "8000:8000"
#    environment:
#      DATABASE_URL: postgres://postgres_user:password@postgres_db:5432/database_name  # Adjust connection details
#    depends_on:
#      - postgres_db
#
  frontend:
    build:
      dockerfile: DockerfileFrontend
    container_name: frontend
    ports:
      - "4200:80"
#    depends_on:
#      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your custom Nginx configuration
    depends_on:
      - frontend

#  postgres_db:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres_user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: database_name
#    ports:
#      - "5432:5432"
