version: '3.8'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ~/pg_data:/var/lib/postgresql/data
  backend:
    build:
      context: app
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_ENDPOINT=${DB_ENDPOINT}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    depends_on:
      - postgres
  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${NGINX_PORT}"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - frontend