version: '3.8'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - "./pg_data:/var/lib/postgresql/data"

  backend:
    build:
      context: app
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file: .env
    depends_on:
      - postgres
  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${NGINX_PORT}"
    depends_on:
      - backend
  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - frontend