name: BACKUP CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
  pull_request:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: backup-pipeline.yml
          workflow_conclusion: success
          name: versions-artifact
          if_no_artifact_found: warn
      - run: |
          if [ -f versions.json ]; then
            mkdir -p ~/backup
            mv versions.json ~/backup
          fi
      - run: ./backup.sh
        env:
          SSH_PRV_KEY: ${{ secrets.SSH_PRV_KEY }}
      - uses: actions/upload-artifact@master
        with:
          name: backup-artifact
          path: ~/backup/
      - uses: actions/upload-artifact@v2
        with:
          name: backup-artifact
          path: ~/backup/*tar.gz
          retention-days: 5
      - uses: actions/upload-artifact@v2
        with:
          name: versions-artifact
          path: ~/backup/versions.json
          retention-days: 5