name: Backend. Test, build and push to artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'
defaults:
  run:
    working-directory: app
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: |
          pip install -r requirements.txt
          pip install flake8 pytest httpx pytest-mock
          flake8 .
          pytest tests/
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: be_devops:latest
          outputs: type=docker,dest=/tmp/be_devops.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: be_devops
          path: /tmp/be_devops.tar

  save:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: be_devops
          path: /tmp/be_devops.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: be_devops
          path: /tmp/be_devops.tar
          retention-days: 1