name: Backend. Test, build and push to artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'
defaults:
  run:
    working-directory: app
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: pip install flake8 pytest httpx pytest-mock
      - run: flake8 .
      - run: pytest tests/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: be_devops:latest
          outputs: type=docker,dest=/tmp/be_devops.tar
      - uses: actions/upload-artifact@v3
        with:
          name: be_devops
          path: /tmp/be_devops.tar

  save:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: be_devops
          path: /tmp/be_devops.tar
      - uses: actions/upload-artifact@v2
        with:
          name: be_devops
          path: /tmp/be_devops.tar
          retention-days: 1