name: BACKUP CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
  pull_request:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: continue-on-error Comment
        uses: mainmatter/continue-on-error-comment@v1
#        continue-on-error: true

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: versions-artifact
          path: ~/

      - name: Use Downloaded Artifacts
        run: |
          ls ~/


      - name: Run backup execution
        run: ./backup.sh
        env:
          SSH_PRV_KEY: ${{ secrets.SSH_PRV_KEY }}

      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backup-artifact
          path: ~/backup/*tar.gz
          retention-days: 5

      - name: Save versions.json as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: versions-artifact
          path: ~/backup/versions.json
          retention-days: 5
