name: Backend. Test, build and push to ACR
run-name: Backend. Test, build and push to ACR. Commit hash ${{github.sha}}
on:
  workflow_dispatch:
    inputs:
      runs_on:
        type: choice
        description: Runs-on
        options:
          - ubuntu-20.04
          - self-hosted
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'
defaults:
  run:
    working-directory: app
jobs:
  test:
    runs-on: ${{ inputs.runs_on || 'ubuntu-20.04' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run tests
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest httpx pytest-mock
          flake8 .
          pytest tests/
  build_and_deploy:
    needs: test
    runs-on: ${{ inputs.runs_on || 'ubuntu-20.04' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Azure ACR login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Build and upload to Azure ACR'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az acr build --image be_devops:latest \
            --registry ${{secrets.REGISTRY_NAME}} \
            --file Dockerfile .