name: BACKUP CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
  pull_request:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: continue-on-error Comment
        uses: mainmatter/continue-on-error-comment@v1

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ~/backup
          key: ${{ runner.os }}-my-cache
      - run: ls ~/backup

#      - name: Retrieve Cache
#        uses: actions/cache@v3
#        with:
#          path: ~/backup
#          key: ${{ runner.os }}-my-cache

#      - name: Copy Files from Previous Artifact
#        run: |
#          mkdir -p ~/tmp-backup
#          cp -r ~/backup/*.tar.gz ~/tmp-backup/
#          ls ~/tmp-backup/

      - name: Run backup execution
        run: ./backup.sh
        env:
          SSH_PRV_KEY: ${{ secrets.SSH_PRV_KEY }}

#      - name: Copy Files from Previous Artifact v2
#        run: |
#          cp -r ~/tmp-backup/*.tar.gz ~/backup/
#          ls ~/tmp-backup/
#          rm -rf ~/tmp-backup

      - name: Save Cache
        uses: actions/cache@v3
        with:
          path: ~/backup/versions.json
          key: ${{ runner.os }}-my-cache

      - name: Build Docker Image
        run: |
          docker build -t backup_devops:latest .

      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backup-artifact
          path: ~/backup
          retention-days: 5

      - name: Save versions.json as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: versions-artifact
          path: ~/backup/versions.json
          retention-days: 5
