name: BACKEND CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: pip install flake8 pytest httpx pytest-mock
      - run: flake8 .
      - run: pytest tests/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v1
    - run: ls
    - run: docker build -t be_devops:latest app

  save:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: backend-docker-image-${{ github.run_id }}
          path: app
          retention-days: 1
