name: BACKUP CI

on:
  push:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
  pull_request:
    paths-ignore:
      - 'app/**'
      - 'frontend/**'
      - 'nginx/**'
      - '.github/workflows/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: continue-on-error Comment
        uses: mainmatter/continue-on-error-comment@v1

      - name: Run backup execution
        run: ./backup.sh
        env:
          SSH_PRV_KEY: ${{ secrets.SSH_PRV_KEY }}

      - name: Show PRV KET
        run: |
          echo "${{ secrets.SSH_PRV_KEY }}" > ~/.ssh/id_rsa
          ls ~/.ssh


      - name: Download Previous Artifact
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: backup-artifact
          path: backup

      - name: Copy Files from Previous Artifact
        continue-on-error: true
        run: |
          cp -r backup-artifact/*.tar.gz ~/backup/

      - name: Build Docker Image
        run: |
          docker build -t backup_devops:latest .

      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backup-artifact
          path: ~/backup
          retention-days: 5