name: FRONTEND CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
defaults:
  run:
    working-directory: frontend
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          sudo apt update
          sudo apt install -y chromium-browser
      - run: npm install
      - run: npm run lint
      - run: |
          npm ci
          npm run test:ci
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: fe_devops:latest
          outputs: type=docker,dest=/tmp/fe_devops.tar
      - uses: actions/upload-artifact@v3
        with:
          name: fe_devops
          path: /tmp/fe_devops.tar
  save:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: fe_devops
          path: /tmp/fe_devops.tar
      - uses: actions/upload-artifact@v2
        with:
          name: fe_devops
          path: /tmp/fe_devops.tar
          retention-days: 1
