name: FRONTEND CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
defaults:
  run:
    working-directory: frontend
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          sudo apt update
          sudo apt install -y chromium-browser
      - run: npm install
      - run: npm run lint
      - run: |
          npm ci
          npm run test:ci
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t fe_devops:latest .
  save:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-docker-image-${{ github.run_id }}
          path: frontend
          retention-days: 1
