name: Frontend. Test, build and push to artifacts
run-name: Frontend. Test, build and push to artifacts. Commit hash ${{github.sha}}
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
defaults:
  run:
    working-directory: frontend
jobs:
  test:
    runs-on: ubuntu-latest
#    runs-on: self-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install chromium browser
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: Run npm tests
        run: |
          npm install
          npm run lint
          npm ci
          npm run test:ci

  build_and_deploy:
    needs: test
#    runs-on: ubuntu-20.04
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: fe_devops:latest
          outputs: type=docker,dest=/tmp/fe_devops.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fe_devops
          path: /tmp/fe_devops.tar
          retention-days: 1
