name: NGINX CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'nginx/**'
  pull_request:
    paths:
      - 'nginx/**'
defaults:
  run:
    working-directory: ./nginx
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t nginx_devops:latest .
      - uses: ishworkh/container-image-artifact-upload@v1.0.0
        with:
          image: "nginx_devops:latest"
          retention-days: 1