name: NGINX CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'nginx/**'
  pull_request:
    paths:
      - 'nginx/**'
defaults:
  run:
    working-directory: ./nginx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t nginx_devops:latest .

  save:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v2
        with:
          name: nginx-docker-image-${{ github.run_id }}
          path: nginx
          retention-days: 1