name: NGINX CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'nginx/**'
  pull_request:
    paths:
      - 'nginx/**'
defaults:
  run:
    working-directory: ./nginx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: nginx_devops:latest
          outputs: type=docker,dest=/tmp/nginx_devops.tar
      - uses: actions/upload-artifact@v3
        with:
          name: nginx_devops
          path: /tmp/nginx_devops.tar

  save:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: nginx_devops
          path: /tmp/nginx_devops.tar
      - uses: actions/upload-artifact@v2
        with:
          name: nginx_devops
          path: /tmp/nginx_devops.tar
          retention-days: 1