name: Retrieve Artifacts

on:
  workflow_run:
    workflows: ["BACKUP CI"]
    types:
      - completed

jobs:
  retrieve-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: versions-artifact
          path: ~/

      - name: Use Downloaded Artifacts
        run: |
          ls
